name: automated-mobile-testing-integration

on:
  push:
    branches:
      - develop
      - feature/*

  schedule:
    - cron: "00 13 * * TUE"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    environment: dev
    steps:
      - name: checkout
      - uses: actions/checkout@v3
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Install and Run Appium Server
        run: |
          chmod +x ./scripts/RunAppiumServer.sh # install and run appium server in the background
          ./scripts/RunAppiumServer.sh
      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2 # install and create the Emulator
        with:
          api-level: 29
          script: ./gradlew test --info # running our test with info to check the results